volumes:
  dbPostgre:

networks:
  nodenet:
    driver: bridge

services:
  app:
    image: node
    build: 
      dockerfile: Dockerfile
      context: src
    ports:
      - "3000:3000"
    networks:
      - nodenet
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: postgres:17.4
    ports:
      - 5432:5432
    networks:
      - nodenet
    volumes:
      - dbPostgre:/data/db
    environment:
      - POSTGRES_PASSWORD=pwadmin